-- https://github.com/RRethy/base16-nvim/blob/master/lua/base16-colorscheme.lua

local c = {
	offBlack = "#2b303b",
	darkestGrey = "#343d46",
	darkGrey = "#4f5b66",
	midDarkGrey = "#65737e",
	midLightGrey = "#a7adba",
	lightGrey = "#c0c5ce",
	lightestGrey = "#dfe1e8",
	offwhite = "#eff1f5",
	orange = "#d08770",
	yellow = "#ebcb8b",
	oliveGreen = "#a3be8c",
	waterGreen = "#96b5b4",
	blueGrey = "#8fa1b3",
	pink = "#b48ead",
	brick = "#ab7967",
	red = "#bf616a",
}

-- c = {
-- offBlack = "#2b303b",
-- darkestGrey = "#343d46",
-- darkGrey = "#4f5b66",
-- midDarkGrey = "#65737e",
-- midLightGrey = "#a7adba",
-- lightGrey = "#c0c5ce",
-- lightestGrey = "#dfe1e8",
-- offwhite = "#eff1f5",
-- orange = "#e79c9c",
--    -- orange = "#efbdbd",
-- -- yellow = "#ebcb8b",
-- yellow = "#DDD8B8",
-- -- oliveGreen = "#a3be8c",
--    oliveGreen = "#B3CBB9",
-- waterGreen = "#96b5b4",
-- blueGrey = "#8fa1b3",
-- pink = "#bc9cb0",
-- brick = "#a7adba",
-- red = "#bf616a",
-- }

local highlights = {
	Normal = { fg = c.lightGrey, bg = c.offBlack },
	Bold = { bold = true },
	Debug = { fg = c.midLightGrey },
	Directory = { fg = c.blueGrey },
	Error = { fg = c.red, bg = c.offBlack },
	ErrorMsg = { fg = c.midLightGrey, bg = c.offBlack },
	Exception = { fg = c.midLightGrey },
	FoldColumn = { fg = c.waterGreen, bg = c.offBlack },
	Folded = { fg = c.midDarkGrey, bg = c.darkestGrey },
	IncSearch = { fg = c.darkestGrey, bg = c.orange },
	Italic = {},
	Macro = { fg = c.midLightGrey },
	MatchParen = { bg = c.midDarkGrey },
	ModeMsg = { fg = c.oliveGreen },
	MoreMsg = { fg = c.oliveGreen },
	Question = { fg = c.blueGrey },
	Search = { fg = c.darkestGrey, bg = c.yellow },
	Substitute = { fg = c.darkestGrey, bg = c.yellow },
	SpecialKey = { fg = c.midDarkGrey },
	TooLong = { fg = c.midLightGrey },
	Underlined = { fg = c.midLightGrey },
	Visual = { bg = c.darkestGrey },
	VisualNOS = { fg = c.midLightGrey },
	WarningMsg = { fg = c.midLightGrey },
	WildMenu = { fg = c.midLightGrey, bg = c.yellow },
	Title = { fg = c.blueGrey },
	Conceal = { fg = c.blueGrey, bg = c.offBlack },
	Cursor = { fg = c.offBlack, bg = c.lightGrey },
	NonText = { fg = c.midDarkGrey },
	LineNr = { fg = c.darkGrey, bg = c.offBlack },
	SignColumn = { fg = c.midDarkGrey, bg = c.offBlack },
	StatusLine = { fg = c.midLightGrey, bg = c.offBlack },
	StatusLineNC = { fg = c.midLightGrey, bg = c.darkestGrey },
	WinBar = { fg = c.lightGrey },
	WinBarNC = { fg = c.midLightGrey },
	-- VertSplit = { fg = c.red, bg = c.offBlack },
	VertSplit = { fg = c.darkGrey, bg = c.offBlack },
	WinSeparator = { fg = c.darkGrey, bg = c.offBlack },
	ColorColumn = { bg = c.darkestGrey },
	CursorColumn = { bg = c.darkestGrey },
	CursorLine = { bg = c.darkestGrey },
	CursorLineNr = { fg = c.midLightGrey, bg = c.darkestGrey },
	QuickFixLine = { bg = c.darkestGrey },
	PMenu = { fg = c.midLightGrey, bg = c.darkestGrey },
	PMenuSel = { fg = c.darkestGrey, bg = c.lightGrey },
	TabLine = { fg = c.midDarkGrey, bg = c.darkestGrey },
	TabLineFill = { fg = c.midDarkGrey, bg = c.darkestGrey },
	TabLineSel = { fg = c.oliveGreen, bg = c.darkestGrey },
	NvimInternalError = { fg = c.offBlack, bg = c.midLightGrey },
	NormalFloat = { fg = c.midDarkGrey, bg = c.offBlack },
	FloatBorder = { fg = c.blueGrey, bg = c.offBlack },
	NormalNC = { fg = c.lightGrey, bg = c.offBlack },
	TermCursor = { fg = c.offBlack, bg = c.lightGrey },

	TroubleText = { fg = c.midDarkGrey },
	TroubleLocation = { link = "TroubleText" },

	-- Standard syntax
	Boolean = { fg = c.orange },
	Character = { fg = c.midLightGrey },
	Comment = { fg = c.midDarkGrey },
	Conditional = { fg = c.pink },
	Constant = { fg = c.orange },
	Define = { fg = c.pink },
	Delimiter = { fg = c.brick },
	Float = { fg = c.orange },
	Function = { fg = c.blueGrey },
	Identifier = { fg = c.midLightGrey },
	Include = { fg = c.blueGrey },
	Keyword = { fg = c.pink },
	Label = { fg = c.yellow },
	Number = { fg = c.orange },
	Operator = { fg = c.pink },
	PreProc = { fg = c.yellow },
	Repeat = { fg = c.yellow },
	Special = { fg = c.waterGreen },
	SpecialChar = { fg = c.brick },
	Statement = { fg = c.midLightGrey },
	StorageClass = { fg = c.yellow },
	String = { fg = c.oliveGreen },
	Structure = { fg = c.pink },
	Tag = { fg = c.yellow },
	Todo = { fg = c.yellow, bg = c.darkestGrey },
	Type = { fg = c.yellow },
	Typedef = { fg = c.yellow },

	-- Diagnostics
	DiagnosticError = { fg = c.red },
	DiagnosticWarn = { fg = c.pink },
	DiagnosticInfo = { fg = c.blueGrey },
	DiagnosticHint = { fg = c.waterGreen },
	DiagnosticUnderlineError = { fg = c.red, undercurl = true, sp = c.red },
	DiagnosticUnderlineWarning = { undercurl = true, sp = c.orange },
	DiagnosticUnderlineWarn = { undercurl = true, sp = c.orange },
	DiagnosticUnderlineInformation = { undercurl = true, sp = c.pink },
	DiagnosticUnderlineHint = { undercurl = true, sp = c.waterGreen },

	-- LSP
	LspReferenceText = { underline = true, sp = c.midLightGrey },
	LspReferenceRead = { underline = true, sp = c.midLightGrey },
	LspReferenceWrite = { underline = true, sp = c.midLightGrey },
	LspInlayHint = { fg = c.midDarkGrey, italic = true },

	-- Treesitter
	TreesitterContext = { bg = c.darkestGrey, italic = true },

	["@comment"] = { fg = c.midDarkGrey, italic = true },
	["@error"] = { fg = c.midLightGrey },
	["@none"] = { fg = c.lightGrey },
	["@preproc"] = { link = "PreProc" },
	["@define"] = { link = "Define" },
	["@operator"] = { fg = c.lightGrey },
	["@punctuation.delimiter"] = { fg = c.brick },
	["@punctuation.bracket"] = { fg = c.lightGrey },
	["@punctuation.special"] = { fg = c.brick },
	["@string"] = { fg = c.oliveGreen },
	["@string.regex"] = { fg = c.waterGreen },
	["@string.escape"] = { fg = c.waterGreen },
	["@string.special"] = { link = "SpecialChar" },
	["@character"] = { fg = c.midLightGrey },
	["@character.special"] = { link = "SpecialChar" },
	["@boolean"] = { fg = c.orange },
	["@number"] = { fg = c.orange },
	["@float"] = { fg = c.orange },
	["@function"] = { fg = c.blueGrey },
	["@function.call"] = { fg = c.blueGrey },
	["@function.builtin"] = { fg = c.blueGrey, italic = true },
	["@function.macro"] = { fg = c.midLightGrey },
	["@method"] = { fg = c.blueGrey },
	["@method.call"] = { fg = c.blueGrey },
	["@constructor"] = { fg = c.blueGrey },
	["@parameter"] = { fg = c.lightGrey },
	["@keyword"] = { fg = c.pink },
	["@keyword.function"] = { fg = c.pink },
	["@keyword.operator"] = { fg = c.pink },
	["@keyword.return"] = { fg = c.pink },
	["@conditional"] = { fg = c.pink },
	["@repeat"] = { fg = c.pink },
	["@debug"] = { link = "Debug" },
	["@label"] = { fg = c.yellow },
	["@include"] = { fg = c.blueGrey },
	["@exception"] = { fg = c.midLightGrey },
	["@type"] = { fg = c.yellow },
	["@type.builtin"] = { fg = c.yellow, italic = true },
	["@type.qualifier"] = { fg = c.pink },
	["@type.definition"] = { fg = c.yellow },
	["@storageclass"] = { link = "StorageClass" },
	["@attribute"] = { fg = c.yellow },
	["@field"] = { fg = c.lightGrey },
	["@property"] = { fg = c.lightGrey },
	["@variable"] = { fg = c.midLightGrey },
	["@variable.builtin"] = { fg = c.midLightGrey, italic = true },
	["@constant"] = { fg = c.orange },
	["@constant.builtin"] = { fg = c.orange, italic = true },
	["@constant.macro"] = { fg = c.midLightGrey },
	["@namespace"] = { fg = c.midLightGrey },
	["@symbol"] = { fg = c.oliveGreen },
	["@text"] = { fg = c.lightGrey },
	["@text.diff.add"] = { link = "DiffAdd" },
	["@text.diff.delete"] = { link = "DiffDelete" },
	["@text.strong"] = { bold = true },
	["@text.emphasis"] = { fg = c.orange, italic = true },
	["@text.underline"] = { fg = c.offBlack, underline = true },
	["@text.strike"] = { fg = c.offBlack, strikethrough = true },
	["@text.title"] = { fg = c.blueGrey },
	["@text.literal"] = { fg = c.orange },
	["@text.uri"] = { fg = c.orange, underline = true },
	["@text.math"] = { link = "Number" },
	["@text.environment"] = { link = "Macro" },
	["@text.environment.name"] = { link = "Type" },
	["@text.reference"] = { fg = c.lightGrey },
	["@text.todo"] = { link = "Todo" },
	["@text.note"] = { link = "Tag" },
	["@text.warning"] = { link = "DiagnosticWarn" },
	["@text.danger"] = { link = "DiagnosticError" },
	["@tag"] = { fg = c.midLightGrey },
	["@tag.attribute"] = { fg = c.yellow },
	["@tag.delimiter"] = { fg = c.brick },
	-- Modern capture name aliases
	["@function.method"] = { fg = c.blueGrey },
	["@function.method.call"] = { fg = c.blueGrey },
	["@comment.error"] = { link = "DiagnosticError" },
	["@comment.warning"] = { link = "DiagnosticWarn" },
	["@comment.hint"] = { link = "DiagnosticHint" },
	["@comment.info"] = { link = "DiagnosticInfo" },
	["@comment.todo"] = { link = "Todo" },
	["@diff.plus"] = { link = "DiffAdd" },
	["@diff.minus"] = { link = "DiffDelete" },
	["@diff.delta"] = { link = "DiffChange" },
	["@string.special.url"] = { fg = c.orange, underline = true },
	["@keyword.directive"] = { link = "PreProc" },
	["@keyword.directive.define"] = { link = "Define" },
	["@keyword.storage"] = { link = "StorageClass" },
	["@keyword.conditional"] = { fg = c.pink },
	["@keyword.debug"] = { link = "Debug" },
	["@keyword.exception"] = { fg = c.midLightGrey },
	["@keyword.import"] = { fg = c.blueGrey },
	["@keyword.repeat"] = { fg = c.pink },
	["@variable.parameter"] = { fg = c.lightGrey },
	["@variable.member"] = { fg = c.lightGrey },
	["@module"] = { fg = c.midLightGrey },
	["@number.float"] = { fg = c.orange },
	["@string.special.symbol"] = { fg = c.oliveGreen },
	["@string.regexp"] = { fg = c.waterGreen },
	["@markup.strong"] = { bold = true },
	["@markup.italic"] = { italic = true },
	["@markup.strikethrough"] = { strikethrough = true },
	["@markup.heading"] = { fg = c.blueGrey },
	["@markup.raw"] = { fg = c.orange },
	["@markup.link.url"] = { fg = c.orange, underline = true },
	["@markup.link.label"] = { link = "SpecialChar" },
	["@markup.list"] = { fg = c.brick },

	-- Diff
	DiffAdd = { fg = c.oliveGreen, bg = c.offBlack },
	DiffChange = { fg = c.midDarkGrey, bg = c.offBlack },
	DiffDelete = { fg = c.midLightGrey, bg = c.offBlack },
	DiffText = { fg = c.blueGrey, bg = c.offBlack },
	DiffAdded = { fg = c.oliveGreen, bg = c.offBlack },
	DiffFile = { fg = c.midLightGrey, bg = c.offBlack },
	DiffNewFile = { fg = c.oliveGreen, bg = c.offBlack },
	DiffLine = { fg = c.blueGrey, bg = c.offBlack },
	DiffRemoved = { fg = c.midLightGrey, bg = c.offBlack },

	-- Git
	gitcommitOverflow = { fg = c.midLightGrey },
	gitcommitSummary = { fg = c.oliveGreen },
	gitcommitComment = { fg = c.midDarkGrey },
	gitcommitUntracked = { fg = c.midDarkGrey },
	gitcommitDiscarded = { fg = c.midDarkGrey },
	gitcommitSelected = { fg = c.midDarkGrey },
	gitcommitHeader = { fg = c.pink },
	gitcommitSelectedType = { fg = c.blueGrey },
	gitcommitUnmergedType = { fg = c.blueGrey },
	gitcommitDiscardedType = { fg = c.blueGrey },
	gitcommitBranch = { fg = c.orange, bold = true },
	gitcommitUntrackedFile = { fg = c.yellow },
	gitcommitUnmergedFile = { fg = c.midLightGrey, bold = true },
	gitcommitDiscardedFile = { fg = c.midLightGrey, bold = true },
	gitcommitSelectedFile = { fg = c.oliveGreen, bold = true },

	-- Spelling
	SpellBad = { undercurl = true, sp = c.midLightGrey },
	SpellLocal = { undercurl = true, sp = c.waterGreen },
	SpellCap = { undercurl = true, sp = c.blueGrey },
	SpellRare = { undercurl = true, sp = c.pink },

	-- DAP
	DapUINormal = { link = "Normal" },
	DapUIVariable = { link = "Normal" },
	DapUIScope = { fg = c.blueGrey },
	DapUIType = { fg = c.pink },
	DapUIValue = { link = "Normal" },
	DapUIModifiedValue = { bold = true, fg = c.blueGrey },
	DapUIDecoration = { fg = c.blueGrey },
	DapUIThread = { fg = c.oliveGreen },
	DapUIStoppedThread = { fg = c.blueGrey },
	DapUIFrameName = { link = "Normal" },
	DapUISource = { fg = c.pink },
	DapUILineNumber = { fg = c.blueGrey },
	DapUIFloatNormal = { link = "NormalFloat" },
	DapUIFloatBorder = { fg = c.blueGrey },
	DapUIWatchesEmpty = { fg = c.midLightGrey },
	DapUIWatchesValue = { fg = c.oliveGreen },
	DapUIWatchesError = { fg = c.midLightGrey },
	DapUIBreakpointsPath = { fg = c.blueGrey },
	DapUIBreakpointsInfo = { fg = c.oliveGreen },
	DapUIBreakpointsCurrentLine = { bold = true, fg = c.oliveGreen },
	DapUIBreakpointsLine = { link = "DapUILineNumber" },
	DapUIBreakpointsDisabledLine = { fg = c.darkGrey },
	DapUICurrentFrameName = { link = "DapUIBreakpointsCurrentLine" },
	DapUIStepOver = { fg = c.blueGrey },
	DapUIStepInto = { fg = c.blueGrey },
	DapUIStepBack = { fg = c.blueGrey },
	DapUIStepOut = { fg = c.blueGrey },
	DapUIStop = { fg = c.midLightGrey },
	DapUIPlayPause = { fg = c.oliveGreen },
	DapUIRestart = { fg = c.oliveGreen },
	DapUIUnavailable = { fg = c.darkGrey },
	DapUIWinSelect = { bold = true, fg = c.blueGrey },
	DapUIEndofBuffer = { link = "EndOfBuffer" },
	DapUINormalNC = { link = "Normal" },
	DapUIPlayPauseNC = { fg = c.oliveGreen },
	DapUIRestartNC = { fg = c.oliveGreen },
	DapUIStopNC = { fg = c.midLightGrey },
	DapUIUnavailableNC = { fg = c.darkGrey },
	DapUIStepOverNC = { fg = c.blueGrey },
	DapUIStepIntoNC = { fg = c.blueGrey },
	DapUIStepBackNC = { fg = c.blueGrey },
	DapUIStepOutNC = { fg = c.blueGrey },

	-- Noice
	NoiceCmdlinePopupBorderSearch = { link = "FloatBorder" },
	NoiceCmdlineIconSearch = { link = "Title" },
	NoiceCmdlineIcon = { link = "Title" },
	NoiceVirtualText = { fg = c.midLightGrey },

	-- Coverage
	CoverageCovered = { fg = c.oliveGreen },
	CoverageUncovered = { fg = c.red },

	-- blink
	BlinkCmpMenu = { fg = c.midLightGrey, bg = c.darkestGrey },
	PmenuKind = { fg = c.midDarkGrey },
	--    BlinkCmpMenuBorder = { fg = c.lightGrey, bg = c.lightGrey, bold = false },
	BlinkCmpMenuSelection = { fg = c.darkestGrey, bg = c.midLightGrey },
}

return {
	setup = function()
		vim.cmd("syntax reset")
		if vim.g.colors_name then vim.cmd("hi clear") end
		vim.o.termguicolors = true
		vim.o.background = "dark"
		vim.g.colors_name = "sg"
		for group, hi in pairs(highlights) do
			vim.api.nvim_set_hl(0, group, hi)
		end
	end,
}
