require("nvim-treesitter").setup({
	auto_install = true,
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
		disable = {
			"dockerfile",
		},
	},
	indent = { enable = false },
	ensure_installed = {
		"bash",
		"css",
		"dockerfile",
		"gitignore",
		"go",
		"html",
		"json",
		"lua",
		"markdown",
		"markdown_inline",
		"python",
		"regex",
		"rust",
		"vim",
		"yaml",
        "gotmpl",
        "helm",
        "zig",
	},
})
