# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "[◊](bold green)" 
error_symbol = "[◊](bold red)"

# Remove gopher because I'm not a child.
[golang]
symbol = "go "

[aws]
symbol = "aws "
disabled = false

[buf]
disabled = true

[terraform]
symbol = "tf "

[docker_context]
disabled = false
symbol = "docker-context "

[nix_shell]
disabled = true
