[tools]
bat = "latest"
carapace = "latest"
fd = "latest"
fzf = "latest"
gemini-cli = "latest"
go = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
ripgrep = "latest"
rust-analyzer = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
zig = "latest"
zoxide = "latest"
