[tools]
bat = "latest"
carapace = "latest"
fd = "latest"
fzf = "latest"
gemini-cli = "latest"
gh = "latest"
"github:containers/podman" = { version = "latest", rename_exe = "podman" }
go = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
podman-tui = "latest"
ripgrep = "latest"
rust = "latest"
rust-analyzer = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
zig = "latest"
zoxide = "latest"
